const data = ["Wake up early and start your day with purpose.",
    "Create a to-do list to stay organized and focused.",
    "Practice regular exercise for physical and mental well-being.",
    "Eat a balanced and nutritious diet with plenty of fruits and vegetables.",
    "Stay hydrated by drinking an adequate amount of water daily.",
    "Get sufficient and quality sleep each night.",
    "Read books to expand your knowledge and stimulate your mind.",
    "Practice mindfulness and meditation for mental clarity.",
    "Express gratitude daily for the positive aspects of your life.",
    "Set and work towards achievable goals.",
    "Learn a new skill or hobby regularly to keep your mind active.",
    "Limit screen time and take breaks from technology.",
    "Practice good posture to maintain physical health.",
    "Foster positive relationships with friends and family.",
    "Practice active listening during conversations.",
    "Limit consumption of processed foods and sugars.",
    "Practice deep breathing exercises to reduce stress.",
    "Volunteer and give back to your community.",
    "Keep a journal to reflect on your thoughts and experiences.",
    "Prioritize self-care and engage in activities you enjoy.",
    "Maintain a positive attitude even in challenging situations.",
    "Stay organized by decluttering your living and workspaces.",
    "Set boundaries to maintain a healthy work-life balance.",
    `Learn to say "no" when necessary to avoid overcommitment.`,
    "Regularly review and assess your personal and professional goals.",
    "Practice empathy and understanding towards others.",
    "Cultivate a habit of continuous learning and growth.",
    "Save money and practice budgeting for financial stability.",
    "Stay curious and ask questions to enhance your knowledge.",
    "Practice tolerance and open-mindedness towards diverse perspectives.",
    "Express creativity through art, writing, or other outlets.",
    "Cultivate a growth mindset, embracing challenges as opportunities.",
    "Learn effective stress management techniques.",
    "Develop strong communication skills for effective interaction.",
    "Practice random acts of kindness to make a positive impact.",
    "Plan and prepare healthy meals in advance.",
    "Prioritize mental health and seek support when needed.",
    "Limit exposure to negative news and cultivate a positive media diet.",
    "Engage in regular physical activities for overall health.",
    "Practice good time management to optimize productivity.",
    "Create a habit of expressing and receiving constructive feedback.",
    "Cultivate a sense of humor and find joy in small moments.",
    "Regularly assess and update personal and professional goals.",
    "Take breaks to relax and recharge your mind and body.",
    "Cultivate a habit of environmental consciousness and sustainability.",
    "Foster resilience in the face of challenges.",
    "Regularly assess your financial goals and plan for the future.",
    "Establish and maintain a supportive social network.",
    "Celebrate achievements, both big and small.",
    "Practice mindfulness in daily activities for increased awareness."];

    