// Mapping between words and corresponding emojis
const emojiMapping = {
    'wake': '⏰',
    'early': '🌅',
    'to-do': '📝',
    'organized': '🗃️',
    'exercise': '🏋️‍♂️',
    'physical': '🏃',
    'mental': '🧠',
    'well-being': '💪',
    'balanced': '⚖️',
    'nutritious': '🥦',
    'diet': '🍎',
    'fruits': '🍏',
    'vegetables': '🥕',
    'hydrated': '💧',
    'water': '🚰',
    'sleep': '😴',
    'books': '📚',
    'knowledge': '🧠',
    'mind': '🤔',
    'mindfulness': '🧘',
    'meditation': '🧘‍♂️',
    'gratitude': '🙏',
    'positive': '😊',
    'goals': '🎯',
    'skill': '🛠️',
    'hobby': '🎨',
    'screen time': '📱⏰',
    'breaks': '☕',
    'technology': '🔧',
    'posture': '🚶‍♂️',
    'health': '❤️',
    'relationships': '👫',
    'listening': '👂',
    'processed foods': '🍔🚫',
    'sugars': '🍬🚫',
    'breathing exercises': '🌬️',
    'reduce stress': '😌',
    'volunteer': '🤝',
    'journal': '📓',
    'self-care': '🛁',
    'positive attitude': '😇',
    'challenging situations': '🤨',
    'organized': '🗂️',
    'decluttering': '🧹',
    'living spaces': '🏡',
    'workspaces': '🏢',
    'boundaries': '🚧',
    'work-life balance': '⚖️',
    'say "no"': '🙅‍♂️',
    'overcommitment': '🚫',
    'review': '📋',
    'assess': '🤔',
    'empathy': '🤝',
    'understanding': '🤔',
    'continuous learning': '📚🎓',
    'growth': '🌱',
    'save money': '💰',
    'budgeting': '📊',
    'curious': '🤔',
    'ask questions': '❓',
    'tolerance': '🌍',
    'open-mindedness': '🤯',
    'creativity': '🎨',
    'art': '🎨',
    'writing': '📝',
    'growth mindset': '🌱🧠',
    'effective stress management': '🧘‍♂️',
    'communication skills': '🗣️',
    'random acts of kindness': '🤝',
    'healthy meals': '🥗',
    'mental health': '🧠❤️',
    'support': '🤗',
    'negative news': '🚫📰',
    'positive media diet': '🌐📰',
    'physical activities': '🏃‍♂️',
    'time management': '⌛',
    'optimization': '🔄',
    'expressing': '🗣️',
    'receiving feedback': '👂🔄',
    'sense of humor': '😄',
    'joy': '😊',
    'small moments': '🌈',
    'assess and update goals': '🔄📋',
    'relax': '☕😌',
    'recharge': '⚡',
    'environmental consciousness': '🌍♻️',
    'sustainability': '♻️',
    'resilience': '🌳',
    'challenges': '🏔️',
    'financial goals': '💰🎯',
    'future': '🔮',
    'supportive social network': '🤝',
    'celebrate achievements': '🎉🏆',
    'mindfulness in daily activities': '🧘‍♂️🌍',
  };