name: Build and Deploy iOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    env:
      CI: 1  # Set the CI environment variable

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.1'

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install EAS CLI
      run: npm install -g eas-cli@latest

    - name: Install Dependencies
      run: npm ci

    - name: Build Expo iOS
      run: eas build -p ios

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-build
        path: eas/build
